task : 'summarize'
victim_model : 'codet5'
input : 'pl'
output : 'nl'
lang: 'r'
data_path : '/content/drive/MyDrive/CodeT5/test.jsonl'
victim_model_ckpt: '/content/drive/MyDrive/CodeT5/pytorch_model.bin'
max_source_length: 256
max_target_length: 128
output_path: 'adversarial_attack/generation/output'
mlm_path : 'microsoft/codebert-base-mlm'
output_dir : ''
start : 0
end : 4000
k : 50
threshold_pred_score : 0.3
batch_size : 512
num_label : 0
use_bpe : 1
use_ast_constraint : 1
use_dfg_constraint : 0
use_pred_idx: 1
bleu_theta: 50
